### ISSUE TITLE
Add support of Yandex.Translate

### ISSUE THREAD

**Issue by VadimIpatov** [mshibanami/TranslateWebForSafari#3]
It would be useful to add the Yandex.Translate engine in addition to the existing Google and Bing.

**Comment by mshibanami** [comment]
Oh cool. Thanks @VadimIpatov. Looks pretty easy to implement. Will release the new version for this soon.

**Comment by mshibanami** [comment]
I've submitted the new version for this feature. It would be approved & released by Apple within 2 days.

**Comment by mshibanami** [comment]
Hi @VadimIpatov. Version 1.9 has been released and it supports Yandex.Translate.
Would you please check it again?

**Comment by mshibanami** [comment]
I'm closing this issue but please feel free to reopen it for something unexpected. Thanks.

**Comment by VadimIpatov** [comment]
Hi @mshibanami!
Thanks for so fast implementation! I've tried it, and it works perfectly :)

**Comment by mshibanami** [comment]
Thank YOU @VadimIpatov!!
